"""empty message

Revision ID: 17dec4022f9a
Revises: 79e3c051fb4a
Create Date: 2018-11-17 22:14:54.891077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dec4022f9a'
down_revision = '79e3c051fb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('percentual_entrada', sa.Float(), nullable=True))
    op.add_column('usuario', sa.Column('salario_usuario', sa.Float(), nullable=True))
    op.add_column('usuario', sa.Column('taxa_anual', sa.Float(), nullable=True))
    op.add_column('usuario', sa.Column('valor_maximo_parcelas', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'valor_maximo_parcelas')
    op.drop_column('usuario', 'taxa_anual')
    op.drop_column('usuario', 'salario_usuario')
    op.drop_column('usuario', 'percentual_entrada')
    # ### end Alembic commands ###
