"""empty message

Revision ID: 2bdddd91ad18
Revises: 17dec4022f9a
Create Date: 2018-11-17 22:40:25.396751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdddd91ad18'
down_revision = '17dec4022f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_criacao')
    # ### end Alembic commands ###
