"""empty message

Revision ID: 79e3c051fb4a
Revises: 
Create Date: 2018-11-17 17:06:26.112359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e3c051fb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FGTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('fgts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fgts_id'], ['FGTS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('FGTS')
    # ### end Alembic commands ###
